services:
  mongodb:
    image: mongo:latest

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: yorokobot

    ports:
      - 27017:27017
