refresh_rate: 30 seconds

appenders:

  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"

  rolling_logs:
    kind: rolling_file
    path: logs/yorokobot-latest.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger: # Specify when to switch to another log file 
        kind: size
        limit: 30 mb

      roller: # Specify what to do with older logs files
        kind: fixed_window
        pattern: logs/yorokobot_{}.gz
        count: 10

  rolling_debug:
    kind: rolling_file
    path: logs/traces-latest.log
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5} | {f}:{L} — {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 30 mb
        
      roller:
        kind: fixed_window
        pattern: logs/yorokobot_traces_{}.gz
        count: 20

root:
  level: warn
  appenders:
    - stdout

loggers:
  bot_infos:
    level: info
    appenders:
      - rolling_debug

  bot_warn_errors:
    level: warn 
    appenders:
      - rolling_logs
  
  bot_traces:
    level: debug
    appenders:
      - rolling_debug
