name: code-quality

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Format
        run: cargo fmt --check 

      - name: Lint
        run: cargo clippy

      - name: Tests
        run: cargo test

      - name: Build
        run: cargo build --verbose
